# Generated by Django 4.2.2 on 2023-06-26 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TerceraPreEntregaManceboApp', '0002_detalleventa_cliente_apellido_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='createdAt',
            field=models.DateField(default=datetime.date(2023, 6, 26)),
        ),
    ]
