# Generated by Django 4.2.2 on 2023-06-26 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TerceraPreEntregaManceboApp', '0004_alter_producto_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
